apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
  name: egressip1
spec:
  egressIPs:
  - 10.0.48.101
  - 10.0.48.102
  podSelector:
    matchLabels:
      team: red 
  namespaceSelector:
    matchLabels:
      department: qe
